# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Dark Mode (true/false/never)
darkmode: never

# Personal info
name: Hubert Pruszyński
author: Hubert Pruszyński
title: IT Expert, Solution & Software Architect
email: hubert@hp.net.pl
locale: en_US
# website: hp.net.pl
github_username:  hp-net
linkedin_username: hubertpruszynski


# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-address-card
  url: https://resume.hp.net.pl/resume.pdf
  track: DOWNLOAD_CV

about_title: About Me
about_profile_image: images/profile.webp
about_content: | 
  Hi, my name's Hubert and I'm a Senior IT Architect. As well as designing software 
  I also have experience making software and web apps. I have worked on a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java</mark>, <mark>Microservices</mark> and <mark>Cloud</mark>

  According to [FRIS](https://fris.pl) my thinking style is <mark>Visionary</mark> and my behavioural style is <mark>Individualist</mark>.

content:
  - title: Work in progress
    layout: text
    print: false
    content: | 
      - Writing a book with my friend for people that want to start their career in IT 
      - Mentoring program at Hycom
  - title: Projects 
    layout: projects 
  - title: Offering
    layout: offerings
    print: false
  - title: Work Experience 
    layout: work-experiences
  - title: Certifications
    layout: text
    content: | 
      - **AWS Certified Cloud Practitioner**
        Issued Oct 2020 · Expires Oct 2023
      - **Train the TrainerTrain the Trainer - Sages**
        Issued Oct 2018 · No Expiration Date
      - **Oracle Certified Associate, Java SE 7 Programmer (1Z0-803)**
        Issued Nov 2013 · No Expiration
      - **Oracle ATG Web Commerce 10 Implementation Developer Essentials (1Z0-510)**
        Issued Jul 2012 · No Expiration
      - **ITA101 - Databases (Microsoft IT Academy Programme)**
        Issued Jan 2012 · No Expiration
      - **Oracle ATG Web Commerce 10 PreSales Specialist Assessment**
        Issued Jan 2012 · No Expiration
      - **Oracle ATG Web Commerce 10 Sales Specialist Assessment**
        Issued Jan 2012 · No Expiration
  - title: Education
    layout: text
    content: |
      - 2005 - 2013 **Lodz University of TechnologyLodz University of Technology**

        Engineer's degree, Software Engineering and Data AnalysisEngineer's degree, Software Engineering and Data Analysis
        
        Activities and societies: Member and first president of "Koffeine" scientific club.
  - title: Languages
    layout: text
    content: |
      - **English** - professional working proficiency
      - **Polish** - native proficiency
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering, some of my other interests and hobbies are:
      - My husky dog training
      - Trekking and hiking
      - DIY

# Footer
footer: 
  show_references: false
  # references_title: References on request (Override references text)
  show_references_print: true
  references_title_for_print: Full resume is available at https://resume.hp.net.pl

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

url: https://resume.hp.net.pl

swetrix:
  project_id: xtOfMX5oSmIK

collections:
  projects:
    output: false
  offerings:
    output: false
  work-experiences:
    output: false